Repository Azure/caf-terraform-landingzones-starter, pull requests merged in 2021-04, with the labels that each got.

#52 Hn tf0.15 fix
  enterprise_scale/construction_sets/aks/main.tf
  enterprise_scale/construction_sets/aks/module.tf
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/aks.tfvars
  enterprise_scale/construction_sets/aks/output.tf
Labels: bug

#49 April 2021 Update
  .devcontainer/docker-compose.yml
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  README.md
  configuration/README.md
  configuration/demo/README.md
  configuration/demo/level1/landingzone.tfvars
  configuration/demo/level2/networking/hub/landingzone.tfvars
  configuration/demo/level2/networking/hub/resource_groups.tfvars
  configuration/demo/level2/shared_services/automations.tfvars
  configuration/demo/level2/shared_services/landingzone.tfvars
  configuration/demo/level2/shared_services/recovery_vaults.tfvars
  configuration/demo/level2/shared_services/resource_groups.tfvars
  configuration/demo/level3/aks/README.md
  configuration/demo/level3/data_analytics/101-aml-workspace/README.md
  configuration/demo/level3/data_analytics/101-aml-workspace/landingzone.tfvars
  configuration/sandpit/README.md
  configuration/sandpit/level0/azure_devops/README.md
  configuration/sandpit/level0/azure_devops/azure_devops.tfvars
  configuration/sandpit/level0/azure_devops/configuration.tfvars
  configuration/sandpit/level0/launchpad/dynamic_secrets.tfvars
  configuration/sandpit/level1/README.md
  configuration/sandpit/level1/landingzone.tfvars
  configuration/sandpit/pipelines/README-pipelines.md
Labels: bug, enhancement

#50 Iac and Terratest tests for Secure AKS Construction Set
  .github/workflows/deploy-secure-aks-baseline.yaml
  .pipelines/deploy-secure-aks-baseline.yaml
  enterprise_scale/construction_sets/aks/add-ons/flux/flux.tf
  enterprise_scale/construction_sets/aks/add-ons/flux/main.tf
  enterprise_scale/construction_sets/aks/add-ons/flux/providers.tf
  enterprise_scale/construction_sets/aks/add-ons/flux/variables.tf
  enterprise_scale/construction_sets/aks/flux.tf
  enterprise_scale/construction_sets/aks/main.tf
  enterprise_scale/construction_sets/aks/module.tf
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/02-aks.md
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/cluster-baseline-settings/aad-pod-identity.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/cluster-baseline-settings/flux.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/cluster-baseline-settings/settings-namespace.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/aks.tfvars
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/launchpad/configuration.tfvars
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/launchpad/dynamic_secrets.tfvars
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/launchpad/iam_role_mapping.tfvars
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/launchpad/keyvaults.tfvars
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/launchpad/storage_accounts.tfvars
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/networking/firewall_application_rule_collection_definition.tfvars
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/workloads/flux.tfvars
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/flux/cluster-baseline-settings.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/flux/flux-system/gotk-components.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/flux/flux-system/gotk-sync.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/flux/flux-system/kustomization.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/iac-pipeline.md
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/levels/1_foundation/parameters
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/levels/2_networking/parameters
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/levels/2_shared_services/parameters
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/levels/3_aks/parameters
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/levels/4_flux/parameters
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/pictures/iac-azdo-pipeline.png
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/pictures/iac-gh-pipeline.png
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/testing.md
  enterprise_scale/construction_sets/aks/scripts/deploy_level_with_rover.sh
  enterprise_scale/construction_sets/aks/scripts/launchpad.sh
  enterprise_scale/construction_sets/aks/test/go.mod
  enterprise_scale/construction_sets/aks/test/go.sum
  enterprise_scale/construction_sets/aks/test/level0_launchpad/launchpad_test.go
  enterprise_scale/construction_sets/aks/test/level1_foundation/ExpectedValues.yml
  enterprise_scale/construction_sets/aks/test/level1_foundation/level1_foundation_test.go
  enterprise_scale/construction_sets/aks/test/level2_shared_services/ExpectedValues.yml
  enterprise_scale/construction_sets/aks/test/level2_shared_services/level2_shared_services_test.go
  enterprise_scale/construction_sets/aks/test/level3_aks/ExpectedValues.yml
  enterprise_scale/construction_sets/aks/test/level3_aks/level3_aks_test.go
  enterprise_scale/construction_sets/aks/test/level4_flux/ExpectedValues.yml
  enterprise_scale/construction_sets/aks/test/level4_flux/level4_flux_test.go
  enterprise_scale/construction_sets/aks/test/main.go
  enterprise_scale/construction_sets/aks/test/run_test.sh
  enterprise_scale/construction_sets/aks/test/util/util.go
  enterprise_scale/construction_sets/aks/variables.tf
Labels: enhancement

#56 ADO Patches
  .pre-commit-config.yaml
  configuration/README.md
  configuration/sandpit/level0/azure_devops/azure_devops.tfvars
  configuration/sandpit/pipelines/end_to_end.yaml
Labels: bug
